language: node_js
node_js:
  - "12.16.1"
jdk:
  - oraclejdk11
script:
  - chmod +x backend/mvnw
  - cd backend && ./mvnw -q clean install
  - ./mvnw test -B
  - ./mvnw -q spring-boot:run &
  - cd ../frontend && npm i
  - npm run build --prod
before_deploy:
  - cd ../backend/target
  - zip -r backend-jar.zip *.jar
  - cd ../..
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_ACCESS_SECRET_KEY
    bucket: j2e-project-front
    region: eu-west-3
    skip_cleanup: true
    local_dir: frontend/dist/frontend
    on:
      branch: feat/Add-Travis-CD
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_ACCESS_SECRET_KEY
    app: j2e-project-backend
    env: J2eProjectBackend-env
    bucket_name: elasticbeanstalk-eu-west-3-623081384592
    region: eu-west-3
    skip_cleanup: true
    zip_file: "backend/target/backend-jar.zip"
    on:
      branch: feat/Add-Travis-CD