language: node_js
node_js:
  - "12.16.1"
jdk:
  - oraclejdk11
script:
  - chmod +x backend/mvnw
  - cd backend && ./mvnw -q clean install
  - ./mvnw test -B
  - ./mvnw -q spring-boot:run &
  - cd ../frontend && npm i
  - npm run build --prod
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_SECRET_KEY
  bucket: j2e-project-front
  region: eu-west-3
  skip_cleanup: true
  local_dir: dist/frontend
  on:
    branch: feat/Add-Travis-CD