version: '3'

services:
  client:
    container_name: j2e-client
    build: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'

  server:
    container_name: j2e-server
    build: backend
    ports:
      - '8082:5000'
    environment:
      SECRET_KEY: ${SECRET_KEY}

  mongo:
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}