version: '3'

services:
  client:
    container_name: j2e-client
    build: frontend
    volumes:
      - './frontend:/app'
    ports:
      - '4201:4200'

  server:
    container_name: j2e-server
    build: backend
    ports:
      - '8081:8080'